### ISSUE TITLE
Frio y calor

### ISSUE THREAD

**Issue by manias21** [sballano/nspanel_thermostat#1]
Seria posible que añadir frio y calor en el nspanel para controlar las dos temperaturas?

**Comment by sballano** [comment]
Si te refieres a controlar las las dos cosas a través de relé no, no se puede, al menos no con la modificación de hardware que hice yo:
https://github.com/sballano/nspanel_thermostat

Ten en cuenta que de fábrica los relés tienen conexión a la fase de alimentación y los sistemas HVAC normalmente esperan solo un contacto, no que los conectes a red... Por tanto el "mod" es imprescindible y al hacerlo nos quedamos con un sólo relé.

**Comment by manias21** [comment]
Yo estaba pensando en asignar solo un rele, 
en modo frio, cuando llego a temperatura de consigna, rele 2 cerrado,
en modo calor cuando llego a temperatura de consigna rele 2 cerrado,
y viceversa cuando aun esta pendiente del rango asignado.

De este modo seria posible controlar ambos medios con un solo rele.
¿Que te parece la idea?

**Comment by sballano** [comment]
Pero qué quieres controlar? una caldera? un aire acondicionado/bomba de calor?
No obstante es cuestión de probarlo, hacer que el software controle el relé en modo frío o en modo calor por supuesto que se podría hacer
Lo que no te recomiendo es que si vas a controlar dos sistemas diferentes es que los conectes entre sí... No conectes la entrada de una caldera con la entrada de un aire acondicionado simultáneamente al mismo relé

**Comment by manias21** [comment]
jeje, esta claro que no me explique.

Controlar la compuerta del conducto de clima, el diagrama de conexion es tres hilos, neutro, cerrado y habierto, entonces... como el nspanel tiene dos reles con la fase en comun, puede utilizarse , uno para apertura y el otro para cierre.

Entonces.... 

Dos funciones en boton0
El boton0  en una pulsacion (paro) envia orden de cerrar compuerta, desactivar rele1 y activando rele0 , mas parar el proceso del trabajo del termostato, pantalla nextion off o brillo cero.

El boton 0 en una nueva pulsacion (marcha) envia orden de  compuerta, desactivar rele0 , activando rele1, mas inicio de pantalla nextion, tomando la referencia si esta en frio o en calor la medicion de temperatura en consigna para aplicar funcion al rele.

Hablemos del boton1,  lo mas practico... Frio/Calor... (por algunos que somos clasicos), añadir un boton en el nextion seria lo esperado.

**Comment by sgregori** [comment]
Hola compañeros, yo también estoy currando con nspanel, esphome y estoy partiendo del código de @sballano 

Mi objetivo es que cuando la temperatura sea inferior en calor, o sea superior en frio, invoque la acción de calor/frio, y con ella lanzo un open_cover y stop_cover via home assistant para abrir y cerrar la rejilla.

El problema es que según la documentación debería hacerlo automático, invocar a cool_action y heat_action, pero no hay manera. 

También he intentado hacer yo mismo las condiciones basandome en si estamos en modo frio o calor, pero tiene tela la historia de las condiciones con lambdas.

Si tengo algún avance os lo comento por aquí, agradecería lo mismo.

Saludos,.

**Comment by manias21** [comment]
lo damos por perdido
