### ISSUE TITLE
.tft upload throws and error with latest version.

### ISSUE THREAD

**Issue by shoog03** [sballano/nspanel_thermostat#3]
I see that you have just updated the Yaml file which now compiles successfully. Unfortunately the .tft file seems to be incompatible with the new Yaml since it throws the error:

W][nextion:405]: Nextion reported variable name invalid!

**Comment by sballano** [comment]
just updated it to the same I have in my device

**Comment by shoog03** [comment]
Thanks for the effort, but it still throws the same error when looking for the tft and no update button appears on the HA devices page.

**Comment by sballano** [comment]
did you upload the tft file to the nspanel in the first place? you need a webserver to store the file and trigger the upload from a home assistant service
you can see the process here: https://www.youtube.com/watch?v=Kdf6W_Ied4o (around time 32:40)

**Comment by shoog03** [comment]
OK that did it. I expected to see the upload enabled in the device page. Thanks for all the assistance.

**Comment by shoog03** [comment]
One final question, the panel is in Spanish, is this defined within the tft file ?

**Comment by sballano** [comment]
glad it worked!

The text is all in the yaml file, should be easy to change, just the week days and a couple of strings for the buttons

**Comment by shoog03** [comment]
Making progress, I found and corrected the labels and updated the days of the week - but I don't think its drawing in the date and calculating the correct day of the week. Its stuck on Sat and 8/1 at the moment. I am trying to work out the logic of homeassistant.now but cant find many references to it as yet.

**Comment by shoog03** [comment]
Hi I have everything working and its just what I needed.
I found an error in the original Yaml code which was preventing the date from ever been generated past day 6 of the month;

if ((dia>0)&&(dia<7)&&(mes>0)&&(mes<13))

dia<7 should be dia<32

Cheers for the input.

**Comment by sballano** [comment]
I was not able to check my panel today but thanks for coming back with the fix!
I suppose it says something about my attention, not noticing that mistake for over two years of use of the device! XD
